PDFtoQA:
  pdf_path: "Tesi - Fiscarelli Antonio.pdf"
  output_path: "data/QAtest.json"
  model_id: "ollama_chat/qwen2.5:3b"
  tokenizer_repo: "meta-llama/Llama-3.2-1B"

finetuning:
  dataset_path: "data"
  base_model: "meta-llama/Llama-3.2-1B"
  output_dir: "outputs"
  repo_id: "AntonioFisk/llama3.2-lora-finetuned"